title: Daniel-Krajnik-com
email: krajnik.dan@gmail.com
description: > 
  Full Stack Architectural Assistant. Making architecture cool.

markdown: kramdown

includes_dir: assets

collections:
  static-files:
    collections_dir: assets/Daniel-Krajnik-Portfolio.pdf
    output: true
    permalink: /omega/:name